[package]
name = "chipy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorized = "1.0.0"
getset = "0.1.2"
indexmap = "1.9.3"
smallvec = "1.10.0"
